name: automatsoft

services:
  seguridad-mysql:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: seguridad-mysql
        target: /var/lib/mysql
      - type: bind
        source: ./db/seguridad/schema.sql
        target: /docker-entrypoint-initdb.d/1.sql
      - type: bind
        source: ./db/seguridad/valores_iniciales.sql
        target: /docker-entrypoint-initdb.d/2.sql
    environment:
      MYSQL_ROOT_PASSWORD: 'Admin/123'
      MYSQL_USER: 'test'
      MYSQL_PASS: 'pass'

  seguridad-app:
    build:
      context: ./.devcontainer/
      args:
        - git_user=davidsgv
        - git_mail=davidsgv98@gmail.com
    depends_on:
      - seguridad-mysql
    ports:
      - "8081:80"
    environment:
      - "GO111MODULE=on"
    volumes:
      - ./:/workspaces:cached
      - type: volume
        source: seguridad-data
        target: /data
    stdin_open: true
    tty: true

networks:
  app:
    driver: bridge

volumes:
  seguridad-mysql:
  seguridad-data:
